# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

use_frameworks!

target 'Pinch' do
	pod 'AFNetworking'
	pod 'TTTAttributedLabel'
	pod 'AHEasing'
	pod 'JCTagListView'
	pod 'SwiftValidator'
	pod 'UIView+Shake'
	pod 'Parse'
end

target 'PinchTests' do

end

target 'PinchUITests' do

end

