# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

use_frameworks!

target 'Pinch' do
	pod 'AFNetworking'
	pod 'TTTAttributedLabel'
	pod 'AHEasing'
	pod 'SwiftValidator'
	pod 'UIImageEffects'
	pod 'UIView+Shake'
	pod 'Parse'
    pod 'JCTagListView', :git => "git@github.com:flamencoflsh/JCTagListView.git"
end

target 'PinchTests' do

end

target 'PinchUITests' do

end

